openapi: 3.0.1
info:
  title: Authentication API
  description: API for user authentication including signup and login.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /authenticate/signup:
    post:
      summary: User signup
      description: Register a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                  format: email
                roles:
                  type: array
                  items:
                    type: string
              required:
                - username
                - password
                - email
                - roles
      responses:
        "200":
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: Username is already taken
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /authenticate/login:
    post:
      summary: User login
      description: Authenticate a user and return a JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  type:
                    type: string
                  refreshToken:
                    type: string
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
                    format: email
                  roles:
                    type: array
                    items:
                      type: string
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  status:
                    type: integer
                  error:
                    type: string
                  path:
                    type: string